export default {
  id_g_numpart: 'g-num-part',
  id_g_datelot: 'g-date-lot',
  id_g_turn: 'g-turn',
  id_g_lot: 'g-lot',
  id_g_operation: 'g-operation',
  id_g_totalqty: 'g-total-quantity',
  id_g_standar: 'g-standar',
  id_g_receptiondate: 'g-reception-date',
  id_g_expirationday: 'g-expiration-days',
  id_g_expirationdate: 'g-expiration-date',
  id_g_unit: 'g-unit',
  id_g_secuence: 'g-secuence',
  // datos para editar la etiqueta
  id_r_numpart: 'r-num-part',
  id_r_folio: 'r-folio',
  id_r_lot: 'r-lot',
  id_r_operation: 'r-operation',
  id_r_register: 'r-register',
  id_r_quantity: 'r-quantity',
  id_r_receptiondate: 'r-reception-date',
  id_r_expirationday: 'r-expiration-days',
  id_r_expirationdate: 'r-expiration-date',
  id_r_unit: 'r-unit',
  id_r_secuence: 'r-secuence'
}
